field: 0bf645fd-7d99-41a4-9629-43932758378e
fieldLayouts:
  95d0173d-c3fb-43c1-bcd4-4f60211c3898:
    tabs:
      -
        elements:
          -
            fieldUid: 4ae6986f-47f5-4fcb-ad46-cb327941e5f3
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 55019867-58a7-4cf0-b080-7cc651ffa359
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc8fc9fc-ac85-442d-b74d-c86aee2ea803
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4ae6986f-47f5-4fcb-ad46-cb327941e5f3:
    contentColumnType: string
    fieldGroup: null
    handle: HeroBannerImage
    instructions: ''
    name: 'Hero Banner Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:8c3a1641-c24c-4273-848b-70f525c1782f'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8c3a1641-c24c-4273-848b-70f525c1782f'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  55019867-58a7-4cf0-b080-7cc651ffa359:
    contentColumnType: text
    fieldGroup: null
    handle: HeroBannerTitle
    instructions: ''
    name: 'Hero Banner Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fc8fc9fc-ac85-442d-b74d-c86aee2ea803:
    contentColumnType: string(255)
    fieldGroup: null
    handle: heroBannerCta
    instructions: ''
    name: 'Hero Banner CTA'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: slide
name: Slide
sortOrder: 1
