contentColumnType: text
fieldGroup: ed65131d-698e-495d-8172-b06892001b5c
handle: activitiesIntroduction
instructions: ''
name: 'Activities - Introduction'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
