contentColumnType: text
fieldGroup: 946916b0-0055-4cd6-ab4a-8e6501d18e9b
handle: placesMeta
instructions: ''
name: 'Places - Meta'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
