enableVersioning: true
handle: activities
name: Activities
propagationMethod: all
siteSettings:
  3893ba7e-f883-4de0-9e4a-26c6ae962cf2:
    enabledByDefault: true
    hasUrls: true
    template: activities/_entry
    uriFormat: 'activities/{slug}'
type: channel
