enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  3893ba7e-f883-4de0-9e4a-26c6ae962cf2:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
