enableVersioning: true
handle: packages
name: Packages
propagationMethod: all
siteSettings:
  3893ba7e-f883-4de0-9e4a-26c6ae962cf2:
    enabledByDefault: true
    hasUrls: true
    template: packages/_entry
    uriFormat: 'packages/{slug}'
type: channel
