enableVersioning: true
handle: places
name: Places
propagationMethod: all
siteSettings:
  3893ba7e-f883-4de0-9e4a-26c6ae962cf2:
    enabledByDefault: true
    hasUrls: true
    template: places/_entry
    uriFormat: 'places/{slug}'
type: channel
